# Exported from Render on 2025-06-15T01:30:53Z
services:
- type: web
  name: bot
  runtime: docker
  repo: https://github.com/bnrazaq/bot
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
version: "1"
